[package]
name = "factorio_server"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.63"
tokio = { version = "1.39.3", features = ["full"]}
rand = "0.8.5"
notify = "6.1.1"
futures = "0.3.30"
sysinfo = "0.31.4"
rcon = { version = "0.6.0", features = ["rt-tokio"] }
